ARG SERVICE_NAME=csc302

FROM node:8 AS base

# Install dependencies
RUN npm install webpack webpack-cli webpack-node-externals nodemon

# Wait binary for Mongo Daemon
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /usr/local/bin/wait
RUN chmod +x /usr/local/bin/wait

WORKDIR /app

ADD package.json .
ADD package-lock.json .

RUN npm install