export const FormConstants = {
  GET_FORM_LIST_REQUEST: 'GET_FORM_LIST_REQUEST',
  GET_FORM_LIST_SUCCESS: 'GET_FORM_LIST_SUCCESS',
  GET_FORM_LIST_AILURE: 'GET_FORM_LIST_FAILURE',

  GET_FORM_REQUEST: 'GET_FORM_REQUEST',
  GET_FORM_SUCCESS: 'GET_FORM_SUCCESS',
  GET_FORM_FAILURE: 'GET_FORM_FAILURE',  

  GET_RESPONSE_REQUEST: 'GET_RESPONSE_REQUEST',
  GET_RESPONSE_SUCCESS: 'GET_RESPONSE_SUCCESS',
  GET_RESPONSE_FAILURE: 'GET_RESPONSE_FAILURE',

  ADD_FORM_RESPONSE_REQUEST: 'ADD_FORM_RESPONSE_REQUEST',
  ADD_FORM_RESPONSE_SUCCESS: 'ADD_FORM_RESPONSE_SUCCESS',
  ADD_FORM_RESPONSE_FAILURE: 'ADD_FORM_RESPONSE_FAILURE',

  GET_RESPONSE_ANSWER_REQUEST: 'GET_RESPONSE_ANSWER_REQUEST',
  GET_RESPONSE_ANSWER_SUCCESS: 'GET_RESPONSE_ANSWER_SUCCESS',
  GET_RESPONSE_ANSWER_FAILURE: 'GET_RESPONSE_ANSWER_FAILURE',

  ADD_FORM_RESPONSE_CHOICE_ANSWER_REQUEST: 'ADD_FORM_RESPONSE_CHOICE_ANSWER_REQUEST',
  ADD_FORM_RESPONSE_CHOICE_ANSWER_SUCCESS: 'ADD_FORM_RESPONSE_CHOICE_ANSWER_SUCCESS',
  ADD_FORM_RESPONSE_CHOICE_ANSWER_FAILURE: 'ADD_FORM_RESPONSE_CHOICE_ANSWER_FAILURE',

  ADD_FORM_RESPONSE_FIELD_ANSWER_REQUEST: 'ADD_FORM_RESPONSE_FIELD_ANSWER_REQUEST',
  ADD_FORM_RESPONSE_FIELD_ANSWER_SUCCESS: 'ADD_FORM_RESPONSE_FIELD_ANSWER_SUCCESS',
  ADD_FORM_RESPONSE_FIELD_ANSWER_FAILURE: 'ADD_FORM_RESPONSE_FIELD_ANSWER_FAILURE',

  DELETE_FORM_RESPONSE_REQUEST: 'DELETE_FORM_RESPONSE_REQUEST',
  DELETE_FORM_RESPONSE_SUCCESS: 'DELETE_FORM_RESPONSE_SUCCESS',
  DELETE_FORM_RESPONSE_FAILURE: 'DELETE_FORM_RESPONSE_FAILURE',

  GET_FORM_RESPONSE_LIST_REQUEST: 'GET_FORM_RESPONSE_LIST_REQUEST',
  GET_FORM_RESPONSE_LIST_SUCCESS: 'GET_FORM_RESPONSE_LIST_SUCCESS',
  GET_FORM_RESPONSE_LIST_FAILURE: 'GET_FORM_RESPONSE_LIST_FAILURE', 

  GET_FORM_QUERY_REQUEST: 'GET_FORM_QUERY_REQUEST',
  GET_FORM_QUERY_SUCCESS: 'GET_FORM_QUERY_SUCCESS',
  GET_FORM_FORM_QUERY_FAILURE: 'GET_FORM_QUERY_FAILURE', 
  
  PUT_FORM_RESPONSE_REQUEST: 'PUT_FORM_RESPONSE_REQUEST',
  PUT_FORM_RESPONSE_SUCCESS: 'PUT_FORM_RESPONSE_SUCCESS',
  PUT_FORM_RESPONSE_FAILURE: 'PUT_FORM_RESPONSE_FAILURE',
};
